### ISSUE TITLE
Can't decrypt data with aes decrypt function in native

### ISSUE THREAD

**Issue by appstute-prasad** [etienne-martin/CryptoJS.swift#10]
I have function used in cross platform application and i want to convert it into native please help me?
```javascript
function fn_decryptData(var_data,var_key){
	var encrypted = CryptoJS.enc.Base64.parse(var_data);
	var encodedString = btoa(var_key);
	var key = CryptoJS.enc.Base64.parse(encodedString);
	var iv = `CryptoJS.enc.Base64.parse('somestring');`
	return (CryptoJS.enc.Utf8.stringify(CryptoJS.AES.decrypt({ ciphertext: encrypted },key,{ mode: CryptoJS.mode.CBC, padding: CryptoJS.pad.Pkcs7, iv: iv,  })));
}
```

How to use this in native to decrypt data

**Comment by etienne-martin** [comment]
You will need my new library for that: https://github.com/etienne-martin/WebCrypto.swift

See https://github.com/etienne-martin/WebCrypto.swift#usage on how to use it.

#### Decryption example:

```swift

// You will need to convert your base64 encoded data to the swift Data type
let encrypted = ... 

let key = "6f0f1c6f0e56afd327ff07b7b63a2d8ae91ab0a2f0c8cd6889c0fc1d624ac1b8"
let iv = "92c9d2c07a9f2e0a0d20710270047ea2"

crypto.decrypt(data: encrypted, key: key, iv: iv, callback: {(encrypted: Data?, error: Error?) in
    print(String(data: decrypted!, encoding: .utf8)!)
})
```
Hope this helps!

**Comment by appstute-prasad** [comment]
I tried to use WebCrypto.swift with following example but i am not getting correct decrypted answer, as Encrypted string given code (input) is "good morning", 


`  let input = "SqPHeh4rWB0zt0cRfv/9uw=="
        let data = Data(input.utf8)
        let key = "password12345678"
        let keydata = Data(key.utf8).base64EncodedString()
        let newKey = crypto.hexEncodedStringFromData(Data(keydata.utf8))
         let iv = "5D9r9ZVzEYYgha93/aUK2w=="
        let ivdata = Data(iv.utf8).base64EncodedString()
      crypto.decrypt(data: data, key: newKey, iv: ivdata) { (decrypted, error) in
            if decrypted != nil {
                print(decrypted!)
  // I am getting wrong data here
            }else {
                print(error!)
            }
            
        }
`

Can you please explain this sample example?

**Comment by appstute-prasad** [comment]
I tried to use WebCrypto.swift with following example but i am not getting
correct decrypted answer, as Encrypted string given code (input) is "good
morning",

let input = "SqPHeh4rWB0zt0cRfv/9uw==" let data = Data(input.utf8) let key
= "password12345678" let keydata = Data(key.utf8).base64EncodedString() let
newKey = crypto.hexEncodedStringFromData(Data(keydata.utf8)) let iv =
"5D9r9ZVzEYYgha93/aUK2w==" let ivdata = Data(iv.utf8).base64EncodedString()
crypto.decrypt(data: data, key: newKey, iv: ivdata) { (decrypted, error) in
if decrypted != nil { print(decrypted!) // I am getting wrong data here
}else { print(error!) } }

Can you please explain this sample example?

**Comment by etienne-martin** [comment]
Hi there,

Please create an issue on https://github.com/etienne-martin/WebCrypto.swift <https://github.com/etienne-martin/WebCrypto.swift>.

Thanks,

Etienne.

**Comment by appstute-prasad** [comment]
I have created this issue you can check it.

Thanks in advance.
