### ISSUE TITLE
Using with hex encoded message and key.

### ISSUE THREAD

**Issue by uditb** [etienne-martin/CryptoJS.swift#12]
Please suggest, how to use it with hex encoded message and key.

**Comment by etienne-martin** [comment]
As stated in the README, this project has been deprecated in favor of https://github.com/etienne-martin/WebCrypto.swift.

The new project has some helper functions to help manipulating hexadecimal:

**Convert Data to hex encoded string:**

```swift
let hex = crypto.hexEncodedStringFromData(data)
```

**Convert hex encoded string to Data:**

```swift
let data = crypto.dataFromHexEncodedString(hex)
```
