### ISSUE TITLE
DES encryption does not work properly

### ISSUE THREAD

**Issue by chenxing890** [etienne-martin/CryptoJS.swift#14]
If you comment out CryptoJS.AES then the DES method will not work. Example: Comment out the ViewController class 16-38 in the project, then CryptoJS.TripleDES() will not work.

**Comment by chenxing890** [comment]
The author changed the CryptoJS library, causing CryptoJS to not work. The solution is to re-download CryptoJS tripledes.js from Google Code, overwrite the tripledes.js in the project, and add the encryptTripleDES, decryptTripleDES, encryptDES added by the author at the bottom of the triples.js , the decryptDES method, this works fine

**Comment by etienne-martin** [comment]
This project has been deprecated in favor of https://github.com/etienne-martin/WebCrypto.swift. 

Feel free to open an issue in the new project if you find any problem.
