### ISSUE TITLE
Not so much an issue as I need help

### ISSUE THREAD

**Issue by maksTheAwesome** [etienne-martin/CryptoJS.swift#4]
Hi first of all I want to thank you for your library.  I'm complete noob to data encryption and just need help with it.

Back-end API uses CryptoJS for encrypting their responses. I've tried your library and looks like it works perfect locally. It was easy. But when I try to decrypt server response it returns result "undefined"

Here is the sample of response:
`
"{\"ct\":\"clK4DaN8jn6uep8Uj42usi/ZfoyWBVjIK8Kx8kds5uf9cwp7l0dUheIrdcJwtgUSw70TKD/zrTYAoiRQQ6f1VxoYFroLzeKn+VWlkmqam69tHA66BOc6POnLChBxa9dOhm3Vju+y5IPTPwcclJvgFHKBsnUCdka0yfg6QvELAHef6J6hIYXnithqcSXgJZYMqlSPI0Y5qhysSj8CT9/EINC/LsHCaVEEi1q7x0BoYZ2VaZHXDKmI7Rpdksca5/BB6VoRP3Bno9r095ymoeljGBgpaY61cJLDCbTC2H500ChuwXz3HtacdtFczEu/ornk9QoRkBGc7G/zV2CMMZuiprz9OIiIrpUDVnkDOp5FljGhGCsXXB5r0tH0g1ajs7b5EUwtXV9xIMbmQTzGogJtTALrfHmp0WofTw16HNygFq/OyGbxTZBHVQlFlEdHtCubyKSSWIPJIyXhIEKaJMoSf74kF0Fmum+6cPtH/1uRcbpPrc7g3sI/7L0aO6vZhOYqtzLnk6ZcgUVx8725fWigwVVZJfVSnh2TKLN61Cyszlk5RgJ7w0Bg3Rx24QRMmpq9P6wMZO9gNabl0nA/1g2Pd8SvGux3Mo5KLqAZtRsFzrTLcZ45gR04bhFEciYce70U6JVYEz474quJNL9EXQ1xqsvdPkXOba/RSVpRecBi/OM0r5JzC2kn6rHkxzRtDeLA3m2pjbmI5eAYtKe/tV4jwNGC3ircPRtF2GaottgG2IoeteKi6qe9boUq6TNKBCZMWpXC98lLZRGZMQ2fXMihIDFtM6BrjfCpc9EYD2ph6SvRHHMcuH5PGwye3N4vsVMCnYadtwBYt80o1Ho7wcbwo26H95LflRg/kf2VeI0GEPYPNluKuwXIrFQysDPiP+DWtynN/yqp+9JQV0qAfCJ+QNGWwBKVQ0wBq0sctFd3UO1Spgb7bsssMXxFRuaKO0Sit7mjVpJTbl4tBRLe66tTN456ANDU9m7rkn61kJ2IYRa417aAgigZXhhkCUfbOi8vm0rfsD42YtnBoHsBcCEf2UGv2sbqX4VXgn4zRs7xYo57rpwPVdoTXd0QJ/xaXllEntWrPZeuLn5Dn42ZjlNRTzwIg3Z5E/VmekkOBJxfZX11q/o4UF0voom4xzy8qkIU2SgdiP2rM0LqQEW/X+sx/0PFnbNYHjkVNYMPZ2sFeCbCuoIKw7t/4HfYIwu4bQpzj1mUV+LybkwFGfd0/UVkADWTZFib9LVcwiGYi7YwbFYdhLAld3R7I08MsLeyiespBsiKWvh1AvGGc+3rJFu35APBk5SvUtGBKmj5T6D+jBIhrAcpW83wrnaz/av4v+5q2eXNyZf447tdCzOmZyExu9R8ZWoo3/QI3F5JwMd3ofpLM8Xuh5yc9HxLtfHZ2OwkMqmOf9lOY6uxFA1Jbt/wt/II4I69inPUIwYGPP9EhM/Wzc9oeyuJb2epvriTSxyJXb+hM351kBJ9qUrI3+A6dr0gDKLRnFNlMy0RbeOal5+a7C4YG5fOA8Huq8fmJDqhDHsTuhZcQC3IqL+PTMGEv08Nxz3y80kAEuPvBpCHr47O8FfwgXU2KrMLfxXP0W/2mYP3O2neS8fL7eiMx4Svzh1fMuha2i0QzntD5mJOyWzBUZnK5x5XOGo8dd8H9/lhY+EEbrHHgTpXTJWdhv5cD7kOPdqthjcZsj/Rh4JSBrV9Yk3nghO9YQD46mif4B2PTPbC00SQ8hpFHt2EZWDJ/WR3cylKKTyzy293R0MHlpKSdKXu1sB/ao6QRTyIn8enxtv1VD1M52K2PgGaUJgm3O9vuKNhTv/bTcMux0ZtrHm828nL2YkOTW7gJtQQh0OESVRgD6thsYvgja7DZC97nMl9fDeaUaOiU5KlM4FTYF09ASSzG1OvheJ+tYDHfQXg\",\"iv\":\"1312f7120c39478c3c1a8695835608aa\",\"s\":\"f63c9a8b42209432\"}"
`

and a key that suppose to help:

`8aa1ec1e6948b481d1ee450c94ffb2edc774877325df4d05aca2e5827497ed33`

**Comment by etienne-martin** [comment]
First, try to decrypt the response with the [javascript version](https://github.com/sytelus/CryptoJS) of CryptoJS. Let me know if it works or not.

**Comment by maksTheAwesome** [comment]
Can you advise the best way to do that? I'm not sure how to run a javascrypt code.

**Comment by etienne-martin** [comment]
Nop, I suggest you ask your questions on [stackoverflow.com](http://stackoverflow.com/search?q=cryptojs).

**Comment by maksTheAwesome** [comment]
I tried a ton of stuff. Could you, please, take a look at my [sample project](https://github.com/maksTheAwesome/decryptorSample) and advise what I'm doing wrong. Cause none of the methods I tried in it aren't working for me.

Here is more detailed description:
http://stackoverflow.com/questions/37579400/cryptoswift-cryptojs-swift

Anyway, thank you for your time.

**Comment by etienne-martin** [comment]
It's not running "out of the box" on my machine.
