### ISSUE TITLE
DES Mode

### ISSUE THREAD

**Issue by vre142** [etienne-martin/CryptoJS.swift#5]
Hi,
Do this library decrypt DES files?
Thanks,
Rafa

**Comment by etienne-martin** [comment]
No but this is something that can be easily implemented.

**Comment by vre142** [comment]
Can you help me about this subject?how can I do it?

**Comment by etienne-martin** [comment]
It's now implemented. 

I hope you were referring to tripleDES and not the weak DES.

Take a look at the updated documentation on how to use DES with CryptoJS.swift.
