### ISSUE TITLE
Does it work with Swift 3?

### ISSUE THREAD

**Issue by rmvz3** [etienne-martin/CryptoJS.swift#7]
Hi. I've converted CryptoJS.swift to Swift 3 using Xcode 8 converter and the converted file seems to be ok but I can't make it work.

When I try

```
    // Load the TripleDES module
     let TripleDES = CryptoJS.TripleDES()

    // Basic TripleDES encryption
    let encrypted = TripleDES.encrypt("secretMessage", secretKey: "password123")
    print("SECRETMESSAGE: " + encrypted)

    // Basic TripleDES decryption
    let decrypted = TripleDES.decrypt(encrypted, secretKey: "password123")
    print("RESULT: " + decrypted)
```

I get:

Loaded tripledes.js
SECRETMESSAGE: Optional(undefined)
RESULT: Optional(undefined)

What am I missing?

**Comment by etienne-martin** [comment]
Thanks for telling me.

I converted the project to swift 3, the problem is fixed.
