### ISSUE TITLE
Encryption options in Swift 3

### ISSUE THREAD

**Issue by CamUni** [etienne-martin/CryptoJS.swift#8]
I'm trying to set the encryption options in swift 3 and I'm able to get the code to compile with the code below

`AES.encrypt(secretMessage: pw, secretKey: key, options: ["mode": CryptoJS.mode.ECB()] as? AnyObject)!
`
However this causes the app to crash when the code is run. Without the `as? AnyObject `the code won't compile and I get the error `Contextual type 'AnyObject' cannot be used with dictionary literal`.

Any suggestions?

**Comment by etienne-martin** [comment]
Thanks for telling me.

I converted the project to swift 3, the problem is fixed.
