### ISSUE TITLE
Swift 3 compiler warnings

### ISSUE THREAD

**Issue by mikecorlett** [etienne-martin/CryptoJS.swift#9]
Using xcode 8.2 I get compiler warnings from the evaluateScript calls, e.g.

cryptoJScontext?evaluateScript(cryptoJS)
the warning is: Expression of type JSValue? is unused

the fix seems to be to change the lines to

let _ = cryptoJScontext?evaluateScript(cryptoJS)

Any comments?

Thanks

**Comment by etienne-martin** [comment]
Thanks, the issue is fixed bfc015d80038dd7791722a0a51211433deaa5d22
